title: Github Pages with Jekyll
author: Alexa B.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Example

# social links
github_username:  runargs

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
